version: '2'

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dogsled
    - err113
    - errorlint
    - exhaustive
    - exhaustruct
    - exhaustruct_v5
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gomodguard # deprecated
    - gosec
    - gosmopolitan
    - ireturn
    - mnd
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - recvcheck
    - unqueryvet
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    govet:
      enable-all: true
      disable: [fieldalignment]
    nolintlint:
      require-specific: true
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - gocognit
          - goconst
          - gocritic
          - lll
          - prealloc
        path: (.+)_test.go
      - linters: [govet]
        text: 'shadow: declaration of "err" shadows declaration'

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra:
        group-params: true
        clothe-returns: true
        balance-calls: true
